### PR TITLE
Fix path not work

### PR DESCRIPTION
**Pull request by nothinux**
fix path if remote script has different name and update readme

### CODE REVIEW

**Comment by MegaphoneJon** [comment]
Thank you @nothinux! I'm no longer at JMA Consulting, but I can merge this (along with another change I'm sitting on) to my fork.  Could you please submit this PR to https://github.com/MegaphoneJon/Nagios-WordPress-Update?

**Comment by JoeMurray** [comment]
Thanks, @nothinux ! @MegaphoneJon as you are the best person to be maintainer, should we delete this repo, then recreate it as a fork of yours? Forking a fork back to the original name makes me think we may run into issues...my git-fu is not strong.

**Comment by MegaphoneJon** [comment]
@JoeMurray @nothinux I did a rewrite of my copy of this today so that Icinga reports the names and versions of the WP plugins/themes needing updates (similar to the Drupal Nagios module).  I somehow never merged these changes in, but I have now, along with some other upstream fixes.  It's up to you if you all want to upgrade to [my version](https://github.com/MegaphoneJon/Nagios-WordPress-Update) but I thought you all might be interested.

**Comment by JoeMurray** [comment]
Thanks for the generous notice, @MegaphoneJoe . @seamuslee001 could you upgrade us to Jon's latest.

**Pull request merged**
